import functools
import os
import re
import uuid
from pathlib import Path
from typing import Annotated, Any

from dotenv import load_dotenv
from fastapi import (
    BackgroundTasks,
    Depends,
    FastAPI,
    File,
    HTTPException,
    Request,
    UploadFile,
    status,
)
from fastapi.middleware.cors import CORSMiddleware
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from sqlalchemy.orm import Session

from backend.agent.agent_engine import agent_app
from backend.config.config import settings
from backend.database.database import get_db
from backend.database.database_manager import RAGDatabaseManager

# Hook directly into your modular core files
from backend.document.document_parser import MultiModalDocumentParser
from backend.models.models import IngestionJob
from backend.schemas.schemas import AgentChatRequest, JobResponse

env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path)

ollama_base_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

from backend.config.config import logger

app = FastAPI(title="LangGraph Multimodal AI Agent Hub API")

# Shared storage path mapping inside Docker Container

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "*",
    ],  # Allow your Next.js dev server origin
    allow_credentials=True,
    allow_methods=["*"],  # Allows POST, OPTIONS, GET, DELETE, etc.
    allow_headers=["*"],
)


@functools.lru_cache
def initialize_rag_services():
    parser = MultiModalDocumentParser(
        base_output_dir=settings.STATIC_ASSET_DIR, batch_size=3
    )
    db_manager = RAGDatabaseManager()
    return parser, db_manager


parser_engine, db_engine = initialize_rag_services()


def clean_deepseek_response(text: str) -> str:
    """Removes the internal <think>...</think> monologue blocks from DeepSeek output."""
    if not text:
        return ""
    cleaned_text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    return cleaned_text.strip()


def extract_final_agent_response(final_state: dict) -> str:
    """Extracts the final AI message and strips both full <think>...</think> blocks

    and orphan </think> tags.
    """
    if not final_state or "messages" not in final_state:
        return "No response generated by the agent."

    messages = final_state["messages"]

    # Locate the last non-empty AI Message
    raw_content = ""
    for msg in reversed(messages):
        content = getattr(msg, "content", None)
        if isinstance(msg, AIMessage) and content:
            # Skip messages that were solely tool call requests
            if getattr(msg, "tool_calls", None) and not content.strip():
                continue
            raw_content = content
            break

    if not raw_content and messages:
        raw_content = getattr(messages[-1], "content", str(messages[-1]))

    # 1. Remove standard <think>...</think> blocks
    cleaned = re.sub(r"<think>.*?</think>", "", raw_content, flags=re.DOTALL)

    # 2. Handle orphan </think> tags (removes everything before and including </think>)
    if "</think>" in cleaned:
        cleaned = cleaned.split("</think>", 1)[-1]

    # 3. Clean up leading stray brackets, brackets from stream artifacts, or extra whitespace
    cleaned = re.sub(r"^[\]\)\s]+", "", cleaned).strip()

    return cleaned if cleaned else raw_content.strip()


def process_batch_ingestion(
    job_id: int,
    file_batch: list[dict],
    chunk_size: int,
    chunk_overlap: int,
    db: Annotated[Session, Depends(get_db)],
):
    # Open a fresh DB session for the background thread

    try:
        total_files = len(file_batch)

        for idx, file_info in enumerate(file_batch, start=1):
            file_path = file_info["path"]
            filename = file_info["filename"]
            try:
                with open(file_path, "rb") as f:
                    file_bytes = f.read()

                # Pass chunk parameters into your parser
                chunks = parser_engine.parse_file(
                    file_bytes,
                    filename,
                    db=db,
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap,
                )

                if chunks:
                    # Atomic database insertion
                    db_engine.insert_document_chunks(chunks, filename)
                    logger.info(f"Finished background indexing for {filename}")

            except Exception as e:
                logger.error(f"Failed background task for {filename}: {e!s}")
                job = (
                    db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
                )
                if job:
                    job.status = "failed"
                    job.error_message = str(e)
                    db.commit()

            finally:
                # Always clean up temporary file from disk when done
                if os.path.exists(file_path):
                    os.remove(file_path)

            # Dynamically calculate progress %
            progress_pct = int((idx / total_files) * 90)  # Reserve 100% for final step

            job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
            if job:
                job.step = f"Processed {idx}/{total_files} files: {filename}"
                job.progress = progress_pct
                db.commit()

            # Clean up temp file
            if os.path.exists(file_path):
                os.remove(file_path)

        # ALL FILES PROCESSED SUCCESSFULLY -> Set to Completed
        job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
        if job:
            job.status = "completed"
            job.step = "All files ingested successfully"
            job.progress = 100
            db.commit()

    except Exception as e:
        # db.rollback()
        job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
        if job:
            job.status = "failed"
            job.error_message = str(e)
            db.commit()

    # finally:
    #     db.close()


# 2. Ingestion Endpoint
@app.post("/vault/ingest-mixed", status_code=status.HTTP_202_ACCEPTED)
async def ingest_mixed_files(
    request: Request,
    background_tasks: BackgroundTasks,
    db: Annotated[Session, Depends(get_db)],
    files: list[UploadFile] = File(...),
    chunk_size: int = 1000,
    chunk_overlap: int = 200,
):
    """
    Accepts large files or ZIP archives, saves them to disk while monitoring disconnections,
    and forwards chunk_size and chunk_overlap to the background parsing job.
    """
    supported_formats = (".pdf", ".docx", ".xlsx", ".pptx", ".csv", ".md", ".txt")
    queued_files = []
    file_names = ",".join([file.filename for file in files])
    job = IngestionJob(uploaded_files=file_names, status="submitted")
    db.add(job)
    db.commit()
    db.refresh(job)
    job_id = job.job_id
    file_batch = []
    try:
        for file in files:
            file_ext = os.path.splitext(file.filename)[-1].lower()
            if file_ext not in supported_formats and file_ext != ".zip":
                job.status = "failed"
                job.error_message = f"Unsupported file format: {file.filename}"
                db.commit()
                raise HTTPException(
                    status_code=400, detail=f"Unsupported format: '{file.filename}'"
                )
            temp_file_id = f"{uuid.uuid4()}_{file.filename}"
            temp_path = os.path.join(settings.TEMP_UPLOAD_DIR, temp_file_id)

            try:
                # Stream disk writes (Phase 1)
                with open(temp_path, "wb") as buffer:
                    while chunk := await file.read(1024 * 1024):  # 1MB blocks
                        if await request.is_disconnected():
                            logger.warning(
                                f"Client disconnected during upload of {file.filename}"
                            )
                            buffer.close()
                            if os.path.exists(temp_path):
                                os.remove(temp_path)

                            # Update job as failed in DB
                            job.status = "failed"
                            job.error_message = (
                                f"Client disconnected during {file.filename} upload."
                            )
                            db.commit()

                            return {
                                "status": "Aborted",
                                "message": f"Client disconnected during {file.filename} upload.",
                            }
                        buffer.write(chunk)
                file_batch.append({"path": temp_path, "filename": file.filename})
            except Exception as e:
                if os.path.exists(temp_path):
                    os.remove(temp_path)

                # Update job as failed in DB
                job.status = "failed"
                job.error_message = str(e)
                db.commit()
                raise e

            # UPDATE JOB STATUS TO 'PROCESSING' ON FIRST VALID FILE

            job.status = "processing"
            job.step = f"Processing {len(file_batch)} file(s)"
            job.progress = 10
            db.commit()
            # Queue ONE background task for the entire batch
            background_tasks.add_task(
                process_batch_ingestion,
                job_id,
                file_batch,
                chunk_size,
                chunk_overlap,
                db,
            )
        return {
            "job_id": job_id,
            "status": "Processing",
            "message": f"{len(queued_files)} file(s) accepted for background ingestion.",
            "files": queued_files,
            "config": {"chunk_size": chunk_size, "chunk_overlap": chunk_overlap},
        }
    except Exception as e:
        logger.error(f"Error during agent execution: {e!s}")
        raise HTTPException(status_code=500, detail=f"Agent Execution Failed: {e!s}")
    # finally:
    #     # Safely close DB connection at the very end of the endpoint handler
    #     db.close()


@app.post("/vault/chat")
async def chat_with_agent(payload: AgentChatRequest):
    # Enforce strict agent instructions using a SystemMessage
    system_prompt = SystemMessage(
        content=(
            "You are an AI data analyst assistant. "
            "When asked to query, analyze, or summarize database tables, YOU MUST USE the available tools "
            "(e.g., query_tabular_database) to fetch the required data. "
            "Do NOT output your internal thoughts or guess data values. "
            "Always format your final response cleanly in Markdown (use Markdown tables for structured data)."
        )
    )

    langgraph_messages = [system_prompt]

    for m in payload.messages:
        if m.content and m.content.strip():
            if m.role == "user":
                langgraph_messages.append(HumanMessage(content=m.content))
            else:
                langgraph_messages.append(AIMessage(content=m.content))

    if len(langgraph_messages) <= 1:
        raise HTTPException(status_code=400, detail="No valid user message provided.")

    node_holder: list[dict[str, Any]] = []
    agent_config = {
        "configurable": {
            "db_manager": db_engine,
            "retrieval_limit": payload.retrieval_k,
            "ollama_base_url": ollama_base_url,
            "temperature": payload.temperature,
            "top_k": payload.top_k,
            "shared_node_container": node_holder,
        }
    }

    try:
        stream_generator = agent_app.stream(
            {"messages": langgraph_messages}, config=agent_config, stream_mode="values"
        )

        final_state = None
        for chunk in stream_generator:
            final_state = chunk

        final_answer = extract_final_agent_response(final_state)

        return {
            "role": "assistant",
            "content": final_answer,
            "inspected_nodes": node_holder,
        }

    except Exception as e:
        logger.error(f"Error during agent execution: {e!s}")
        raise HTTPException(status_code=500, detail=f"Agent Execution Failed: {e!s}")


@app.post("/vault/clear", status_code=status.HTTP_200_OK)
async def clear_database():
    """Wipes the SQLite database and flushes cached files."""
    try:
        db_engine.wipe_all_data()
        tabular_db_path = os.path.join(
            settings.STATIC_ASSET_DIR, "dynamic_tabular_data.db"
        )
        if os.path.exists(tabular_db_path):
            os.remove(tabular_db_path)
        return {
            "status": "Success",
            "message": "All database and tabular states cleared successfully.",
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear database: {e!s}")


@app.get(
    "/job/status/job_id", response_model=JobResponse, status_code=status.HTTP_200_OK
)
async def get_job_status_by_id(job_id: int, db: Annotated[Session, Depends(get_db)]):
    job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job with ID {job_id} not found.",
        )

    return job


@app.post("/job/clear", status_code=status.HTTP_200_OK)
async def clear_jobs(db: Annotated[Session, Depends(get_db)]):
    try:
        db.query(IngestionJob).delete()
        db.commit()
        db.close()
        return {
            "status": "Success",
            "message": "All Jobs Data cleared successfully.",
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear database: {e!s}")
