import functools
import json
import os
import re
import sys
import uuid
from pathlib import Path
from typing import Annotated, Any

from agent.agent_engine import agent_app
from config.config import logger, settings
from db.database import SessionLocal, get_db
from db.database_manager import RAGDatabaseManager

#    Hook directly into your modular core files
from document.document_parser import MultiModalDocumentParser
from dotenv import load_dotenv
from fastapi import (
    BackgroundTasks,
    Depends,
    FastAPI,
    File,
    HTTPException,
    Request,
    UploadFile,
    status,
)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from models.models import IngestionJob
from schemas.schemas import AgentChatRequest, JobResponse
from sqlalchemy.orm import Session

sys.path.append(str(Path(__file__).resolve().parent))
# env_path = Path(__file__).resolve().parent / ".env"
load_dotenv()

ollama_base_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")


app = FastAPI(title="LangGraph Multimodal AI Agent Hub API")

# Shared storage path mapping inside Docker Container

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow your Next.js dev server origin
    allow_methods=["*"],  # Allows POST, OPTIONS, GET, DELETE, etc.
    allow_headers=["*"],
)


@functools.lru_cache
def initialize_rag_services():
    parser = MultiModalDocumentParser(
        base_output_dir=settings.STATIC_ASSET_DIR,
        batch_size=3,
    )
    db_manager = RAGDatabaseManager()
    return parser, db_manager


parser_engine, db_engine = initialize_rag_services()


def clean_tool_artifacts(text: str) -> str:
    if not text:
        return ""

    # 1. Remove "| Tool Outputs Begin | ... | Tool Outputs End |" block markers
    text = re.sub(
        r"\|?\s*Tool Outputs (Begin|End)\s*\|?", "", text, flags=re.IGNORECASE
    )

    # 2. Remove Chunk metadata headers (e.g., [Source File: ... | Chunk ID: ...])
    text = re.sub(r"\[?Source File:.*?Chunk ID:.*?\]?", "", text, flags=re.IGNORECASE)

    # 3. Clean up markdown table separators left behind (|---|---|)
    text = re.sub(r"\|[\s\-:]*\|", "", text)

    # 4. Collapse leftover double pipes or leading/trailing whitespace
    text = re.sub(r"\|+", " ", text)

    return text.strip()


def clean_deepseek_response(text: str) -> str:
    """Removes complete, orphan, and unclosed <think>...</think> monologue blocks

    from DeepSeek model output.
    """
    if not text:
        return ""

    # 1. Remove closed <think>...</think> blocks
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)

    # 2. Handle unclosed <think> tags (if model cut off mid-thought due to max tokens)
    cleaned = re.sub(r"<think>.*$", "", cleaned, flags=re.DOTALL)

    # 3. Handle orphan </think> tags (removes everything before and including </think>)
    if "</think>" in cleaned:
        cleaned = cleaned.split("</think>", 1)[-1]

    # 4. Clean up leading stray brackets, trailing artifacts, and whitespace
    cleaned = re.sub(r"^[\]\)\s]+", "", cleaned).strip()

    return cleaned


def extract_final_agent_response(final_state: dict[str, Any]) -> str:
    """Extracts the final AI message from LangGraph state and strips thinking artifacts."""
    if not final_state or "messages" not in final_state:
        return "No response generated by the agent."

    messages = final_state["messages"]
    raw_content = ""

    # Locate the last non-empty AI Message
    for msg in reversed(messages):
        if isinstance(msg, ToolMessage):
            continue
        if isinstance(msg, AIMessage):
            # Skip messages that are exclusively tool call requests without text
            if (
                getattr(msg, "tool_calls", None)
                and not _extract_text_content(msg.content).strip()
            ):
                continue

            raw_content = _extract_text_content(msg.content)
            if raw_content.strip():
                break

    # Fallback to last message in thread if no valid AIMessage content was matched
    if not raw_content and messages:
        last_msg = messages[-1]
        raw_content = _extract_text_content(getattr(last_msg, "content", str(last_msg)))

    cleaned = clean_deepseek_response(raw_content)
    cleaned = clean_tool_artifacts(cleaned)

    return cleaned if cleaned else raw_content.strip()


def _extract_text_content(content: Any) -> str:
    """Helper to safely coerce string or list-based LangChain message content to a string."""
    if isinstance(content, str):
        return content
    elif isinstance(content, list):
        # Handle structured content blocks: [{"type": "text", "text": "..."}]
        parts = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and block.get("type") == "text":
                parts.append(block.get("text", ""))
        return "".join(parts)
    return str(content) if content else ""


def process_batch_ingestion(
    job_id: int,
    file_batch: list[dict],
    chunk_size: int,
    chunk_overlap: int,
):
    db = SessionLocal()
    failed_files = []

    try:
        total_files = len(file_batch)
        if total_files == 0:
            return

        file_weight = 90.0 / total_files

        for idx, file_info in enumerate(file_batch, start=1):
            file_path = file_info["path"]
            filename = file_info["filename"]
            file_base_progress = (idx - 1) * file_weight

            def update_job_progress(sub_step_desc: str, sub_percent: float):
                calculated_pct = int(file_base_progress + (file_weight * sub_percent))
                job = (
                    db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
                )
                if job:
                    job.step = f"[{idx}/{total_files}] {filename}: {sub_step_desc}"
                    job.progress = calculated_pct
                    db.commit()

            try:
                update_job_progress("Reading file...", 0.05)

                with open(file_path, "rb") as f:
                    file_bytes = f.read()

                # Stage 1: Parse
                chunks = parser_engine.parse_file(
                    file_bytes,
                    filename,
                    db=db,
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap,
                    on_progress=lambda desc, pct: update_job_progress(
                        f"Parsing - {desc}", 0.05 + (pct * 0.45)
                    ),
                )

                # Stage 2: Embed & Insert into Vector DB
                if chunks:
                    db_engine.insert_document_chunks(
                        chunks,
                        filename,
                        on_progress=lambda desc, pct: update_job_progress(
                            f"Vectorizing - {desc}", 0.50 + (pct * 0.45)
                        ),
                    )

            except Exception as e:
                # Log error and continue with the next file instead of aborting all files
                failed_files.append(f"{filename} ({e!s})")
                logger.error(f"Error processing {filename}: {e!s}")

            # finally:
            #     if os.path.exists(file_path):
            #         os.remove(file_path)

            update_job_progress("File finished", 1.0)

        # Final Batch Status Summary
        job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
        if job:
            if failed_files:
                # If some files failed but others passed
                job.status = (
                    "completed" if len(failed_files) < total_files else "failed"
                )
                job.step = (
                    f"Ingestion finished. Failed files: {', '.join(failed_files)}"
                )
                job.progress = 100
            else:
                job.status = "completed"
                job.step = "All files ingested successfully"
                job.progress = 100
            db.commit()

    finally:
        db.close()


# 2. Ingestion Endpoint
@app.post("/vault/ingest-mixed", status_code=status.HTTP_202_ACCEPTED)
async def ingest_mixed_files(
    request: Request,
    background_tasks: BackgroundTasks,
    db: Annotated[Session, Depends(get_db)],
    files: list[UploadFile] = File(...),
    chunk_size: int = 1000,
    chunk_overlap: int = 200,
):
    """
    Accepts large files or ZIP archives, saves them to disk while monitoring disconnections,
    and forwards chunk_size and chunk_overlap to the background parsing job.
    """
    supported_formats = (".pdf", ".docx", ".xlsx", ".pptx", ".csv", ".md", ".txt")
    queued_files = []
    file_names = ",".join([file.filename for file in files])
    job = IngestionJob(uploaded_files=file_names, status="submitted")
    db.add(job)
    db.commit()
    db.refresh(job)
    job_id = int(job.job_id)
    file_batch = []
    try:
        for file in files:
            file_ext = os.path.splitext(file.filename)[-1].lower()
            if file_ext not in supported_formats and file_ext != ".zip":
                job.status = "failed"
                job.error_message = f"Unsupported file format: {file.filename}"
                db.commit()
                raise HTTPException(
                    status_code=400, detail=f"Unsupported format: '{file.filename}'"
                )
            temp_file_id = f"{uuid.uuid4()}_{file.filename}"
            temp_path = os.path.join(settings.TEMP_UPLOAD_DIR, temp_file_id)

            try:
                # Stream disk writes (Phase 1)
                with open(temp_path, "wb") as buffer:
                    while chunk := await file.read(1024 * 1024):  # 1MB blocks
                        if await request.is_disconnected():
                            logger.warning(
                                f"Client disconnected during upload of {file.filename}"
                            )
                            buffer.close()
                            if os.path.exists(temp_path):
                                os.remove(temp_path)

                            # Update job as failed in DB
                            job.status = "failed"
                            job.error_message = (
                                f"Client disconnected during {file.filename} upload."
                            )
                            db.commit()

                            return {
                                "status": "Aborted",
                                "message": f"Client disconnected during {file.filename} upload.",
                            }
                        buffer.write(chunk)
                file_batch.append({"path": temp_path, "filename": file.filename})
            except Exception as e:
                if os.path.exists(temp_path):
                    os.remove(temp_path)

                # Update job as failed in DB
                job.status = "failed"
                job.error_message = str(e)
                db.commit()
                raise e

            # UPDATE JOB STATUS TO 'PROCESSING' ON FIRST VALID FILE

            job.status = "processing"
            job.step = f"Processing {len(file_batch)} file(s)"
            job.progress = 10
            db.commit()
            # Queue ONE background task for the entire batch
            background_tasks.add_task(
                process_batch_ingestion,
                job_id,
                file_batch,
                chunk_size,
                chunk_overlap,
            )
        return {
            "job_id": job_id,
            "status": "Processing",
            "message": f"{len(queued_files)} file(s) accepted for background ingestion.",
            "files": queued_files,
            "config": {"chunk_size": chunk_size, "chunk_overlap": chunk_overlap},
        }
    except Exception as e:
        logger.error(f"Error during agent execution: {e!s}")
        raise HTTPException(status_code=500, detail=f"Agent Execution Failed: {e!s}")
    # finally:
    #     # Safely close DB connection at the very end of the endpoint handler
    #     db.close()


@app.post("/vault/chat")
async def chat_with_agent(payload: AgentChatRequest):
    system_prompt = SystemMessage(
        content=(
            "You are an AI data analyst assistant. "
            "When asked to query, analyze, or summarize database tables, YOU MUST USE the available tools "
            "(e.g., query_tabular_database) to fetch the required data. "
            "Do NOT output your internal thoughts or guess data values. "
            "Always format your final response cleanly in Markdown (use Markdown tables for structured data)."
        )
    )

    langgraph_messages = [system_prompt]

    for m in payload.messages:
        if m.content and m.content.strip():
            if m.role == "user":
                langgraph_messages.append(HumanMessage(content=m.content))
            else:
                langgraph_messages.append(AIMessage(content=m.content))

    if len(langgraph_messages) <= 1:
        raise HTTPException(status_code=400, detail="No valid user message provided.")

    node_holder: list[dict[str, Any]] = []
    agent_config = {
        "configurable": {
            "db_manager": db_engine,
            "retrieval_limit": payload.retrieval_k,
            "ollama_base_url": ollama_base_url,
            "temperature": payload.temperature,
            "top_k": payload.top_k,
            "shared_node_container": node_holder,
        }
    }

    async def event_generator():
        try:
            # Stream events using 'updates' or 'messages' mode
            async for event in agent_app.astream_events(
                {"messages": langgraph_messages}, config=agent_config, version="v2"
            ):
                kind = event["event"]

                # Yield LLM streamed content tokens in real-time
                if kind == "on_chat_model_stream":
                    chunk_text = event["data"]["chunk"].content
                    if chunk_text:
                        # Output Server-Sent Events or plain JSON lines
                        yield f"data: {json.dumps({'type': 'content', 'delta': chunk_text})}\n\n"

            # Send inspect_nodes metadata block after execution finishes
            if node_holder:
                yield f"data: {json.dumps({'type': 'inspected_nodes', 'nodes': node_holder})}\n\n"

            yield "data: [DONE]\n\n"

        except Exception as e:
            logger.error(f"Error during agent streaming: {e!s}")
            yield f"data: {json.dumps({'type': 'error', 'content': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Prevents Nginx/proxy response buffering
        },
    )


@app.post("/vault/clear", status_code=status.HTTP_200_OK)
async def clear_database():
    """Wipes the SQLite database and flushes cached files."""
    try:
        db_engine.wipe_all_data()
        tabular_db_path = settings.DATABASE_URL
        if os.path.exists(tabular_db_path):
            os.remove(tabular_db_path)
        parser_engine.wipe_all_images_and_tables()
        db_engine.init_db()
        return {
            "status": "Success",
            "message": "All database and tabular states cleared successfully.",
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to clear database: {e!s}")


@app.get(
    "/job/status/job_id", response_model=JobResponse, status_code=status.HTTP_200_OK
)
async def get_job_status_by_id(job_id: int, db: Annotated[Session, Depends(get_db)]):
    job = db.query(IngestionJob).filter(IngestionJob.job_id == job_id).first()
    if not job:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Job with ID {job_id} not found.",
        )

    return job


# @app.post("/job/clear", status_code=status.HTTP_200_OK)
# async def clear_jobs(db: Annotated[Session, Depends(get_db)]):
#     try:
#         db.query(IngestionJob).delete()
#         db.commit()
#         db.close()
#         return {
#             "status": "Success",
#             "message": "All Jobs Data cleared successfully.",
#         }
#     except Exception as e:
#         raise HTTPException(status_code=500, detail=f"Failed to clear database: {e!s}")
